version: 1.0.{build}
os: Visual Studio 2014
platform: x64
clone_folder: C:\projects\polyfem
shallow_clone: true
branches:
  only:
    - master
environment:
  matrix:
  - config: Debug
install:
  # - "%PYTHON%\\python.exe -m pip install numpy"
  # - "%PYTHON%\\python.exe -m pip install sympy"
build:
  parallel: true
build_script:
  - cd c:\projects\polyfem
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=%config% -DPOLYFEM_WITH_MISC=ON -G "Visual Studio 15 2017 Win64" ../
  - set MSBuildLogger="C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - set MSBuildOptions=/v:m /p:Configuration=%config% /logger:%MSBuildLogger%
  - msbuild %MSBuildOptions% PolyFEM.sln

test_script:
  - ctest -C %config% --verbose --output-on-failure -j 2