services:
  polyfem:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: polyfem
    volumes:
      - .:/data
    working_dir: /data
    entrypoint: ["/app/polyfem/build/PolyFEM_bin"]
    command: ["--json", "2-cubes-falling.json"]
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    restart: unless-stopped
